### ISSUE TITLE
#Core#OKO

### ISSUE THREAD

**Issue by poloten4uk** [dodayio/Doday#28]
## Idea:
Сreate a global system for managing subsystems

## Task:
Write a spec for the OKO global system

## Requirements:
1. OKO can register all entities of the app - `Entities`, `Spots`, `Modules`, `Routes`, `Tools`, `Extensions`
2. OKO can find a suitable module for a particular `Spot`
3. OKO contains logic for manage `active` status of the modules (replacing active modules)

**Comment by poloten4uk** [comment]
## Spec
1. Create redux dynamic module for `OKO` system
2. Create Actions for registering entities in the system:
- [ ] registerModule(module: ReduxModule | ViewModule)
- [ ] registerEntity(entity: EntityConfig)
- [ ] registerRoute(route: RouteModel)
- [ ] registerSpot(spot: SpotObject, parent: SpotSysname)
3. OKO redux state shape:
```
{
  redux: {
    [key: ModuleSysname]: ReduxModule;
  };
  modules: {
    [key: SpotSysname]: ViewModule | ViewModule[];
  };
  spots: SpotsTree;
  entities: EntityConfig[];
  routes: {
    [key: RouteSysname]: RouteModel[];
  };
}
```
4. Create Actions for get / set operations:
- [ ] getSuitableModule(props: SpotObjectProps)
- [ ] getModule(sysname: ModuleSysname)
- [ ] getModuleForSpot(spot: SpotSysname)
- [ ] setActiveModule(module: ViewModule, spot: SpotSysname)
